import './config/load-env-file.js';
import { loadEnv } from './config/env.js';
import { prisma } from './infrastructure/db/prisma.js';
import { createRedis } from './infrastructure/redis/redis-client.js';
import { DocumentStorage } from './infrastructure/storage.js';
import { loadConfiguredAdapters } from './adapters/configured.js';
import { WhatsAppClient } from './adapters/whatsapp/whatsapp-client.js';
import { WorkflowService } from './core/workflow-service.js';
import { createQueues } from './queue/queues.js';
import { ActionExecutor } from './queue/action-executor.js';
import { startWorkers } from './queue/workers.js';
import { createServer } from './api/server.js';
const env=loadEnv();
if(env.DATA_MODE==='mock')throw new Error('USE_TEST_SETUP_FOR_MOCK_DATA');
const {redis,redlock}=createRedis(env.REDIS_URL);
const queues=createQueues(redis,env.QUEUE_PREFIX);
const adapterEnvironment={...process.env,KMALEON_CONFIG_FILE:env.KMALEON_CONFIG_FILE,APUDATA_CONFIG_FILE:env.APUDATA_CONFIG_FILE,SEDE_RECIPE_FILE:env.SEDE_RECIPE_FILE};
const adapters=await loadConfiguredAdapters(adapterEnvironment);
const whatsapp=env.SERVICE_MODE==='live'&&env.WHATSAPP_ENABLED&&env.WA_ACCESS_TOKEN&&env.WA_PHONE_NUMBER_ID?new WhatsAppClient({accessToken:env.WA_ACCESS_TOKEN,phoneNumberId:env.WA_PHONE_NUMBER_ID,apiVersion:env.WA_GRAPH_VERSION,transport:env.WHATSAPP_TRANSPORT,apiBaseUrl:env.WA_API_BASE_URL,writesEnabled:env.OUTBOUND_ENABLED,allowedRecipients:env.DEMO_DATA_ENABLED?env.DEMO_WHATSAPP_RECIPIENTS:undefined,maxMediaBytes:env.MAX_DOCUMENT_BYTES,...(process.env.WCE_MEDIA_DIR?{emulatorMediaDir:process.env.WCE_MEDIA_DIR}:{})}):undefined;
const flow=new WorkflowService(prisma,redlock,new DocumentStorage(env.STORAGE_DIR,env.MAX_DOCUMENT_BYTES),env);
const executor=new ActionExecutor(flow,adapters,whatsapp,queues);
const server=await createServer(flow,executor,queues,redis);
redis.on('error',()=>server.log.error('Redis unavailable'));
redlock.on('error',()=>server.log.warn('Case lock unavailable'));
await prisma.$connect();await redis.ping();
const workers=env.WORKERS_ENABLED?startWorkers(flow,executor,queues,redis,server.log):undefined;
let stopping=false;
async function stop(){if(stopping)return;stopping=true;await server.close();await workers?.close();await Promise.all(Object.values(queues).map(q=>q.close()));await redis.quit();await prisma.$disconnect();}
process.once('SIGINT',()=>{void stop().then(()=>process.exit(0));});process.once('SIGTERM',()=>{void stop().then(()=>process.exit(0));});
await server.listen({host:env.HOST,port:env.PORT});
server.log.info({outboundEnabled:env.OUTBOUND_ENABLED},'APOD ready');
